-- MySQL Script generated by MySQL Workbench
-- Tue Jul 13 21:25:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sysperitos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sysperitos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sysperitos` ;
USE `sysperitos` ;

-- -----------------------------------------------------
-- Table `sysperitos`.`fiscales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysperitos`.`fiscales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_fiscal` VARCHAR(60) NULL DEFAULT NULL,
  `rut_fiscal` VARCHAR(12) NULL DEFAULT NULL,
  `estado` TINYINT NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sysperitos`.`peritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysperitos`.`peritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_perito` VARCHAR(60) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `estado` TINYINT NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sysperitos`.`tipo_peritaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysperitos`.`tipo_peritaje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gls_tipo` VARCHAR(45) NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `estado` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sysperitos`.`peritajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysperitos`.`peritajes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ruc` VARCHAR(12) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `nue` VARCHAR(45) NULL DEFAULT NULL,
  `plazo` INT NULL DEFAULT NULL,
  `gls_peritaje` VARCHAR(255) NULL DEFAULT NULL,
  `obs_peritaje` VARCHAR(255) NULL DEFAULT NULL,
  `estado` TINYINT NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `tipo_peritaje_id` INT NOT NULL,
  `fiscales_id` INT NOT NULL,
  `peritos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_peritaje_id`, `fiscales_id`, `peritos_id`),
  INDEX `fk_peritajes_tipo_peritaje1_idx` (`tipo_peritaje_id` ASC) VISIBLE,
  INDEX `fk_peritajes_fiscales1_idx` (`fiscales_id` ASC) VISIBLE,
  INDEX `fk_peritajes_peritos1_idx` (`peritos_id` ASC) VISIBLE,
  CONSTRAINT `fk_peritajes_fiscales1`
    FOREIGN KEY (`fiscales_id`)
    REFERENCES `sysperitos`.`fiscales` (`id`),
  CONSTRAINT `fk_peritajes_peritos1`
    FOREIGN KEY (`peritos_id`)
    REFERENCES `sysperitos`.`peritos` (`id`),
  CONSTRAINT `fk_peritajes_tipo_peritaje1`
    FOREIGN KEY (`tipo_peritaje_id`)
    REFERENCES `sysperitos`.`tipo_peritaje` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sysperitos`.`tipo_act`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysperitos`.`tipo_act` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gls_tipoact` VARCHAR(45) NULL DEFAULT NULL,
  `estado` TINYINT NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sysperitos`.`ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysperitos`.`ubicacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gls_ubicacion` VARCHAR(60) NULL DEFAULT NULL,
  `estado` TINYINT NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sysperitos`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysperitos`.`actividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_act` DATE NULL DEFAULT NULL,
  `estado` TINYINT NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `tipo_act_id` INT NOT NULL,
  `ubicacion_id` INT NOT NULL,
  `peritajes_id` INT NOT NULL,
  `obs_actividad` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `tipo_act_id`, `ubicacion_id`, `peritajes_id`),
  INDEX `fk_actividades_tipo_act1_idx` (`tipo_act_id` ASC) VISIBLE,
  INDEX `fk_actividades_ubicacion1_idx` (`ubicacion_id` ASC) VISIBLE,
  INDEX `fk_actividades_peritajes_idx` (`peritajes_id` ASC) VISIBLE,
  CONSTRAINT `fk_actividades_peritajes`
    FOREIGN KEY (`peritajes_id`)
    REFERENCES `sysperitos`.`peritajes` (`id`),
  CONSTRAINT `fk_actividades_tipo_act1`
    FOREIGN KEY (`tipo_act_id`)
    REFERENCES `sysperitos`.`tipo_act` (`id`),
  CONSTRAINT `fk_actividades_ubicacion1`
    FOREIGN KEY (`ubicacion_id`)
    REFERENCES `sysperitos`.`ubicacion` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sysperitos`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysperitos`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gls_estado` VARCHAR(45) NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `estado` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sysperitos`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysperitos`.`solicitud` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_sol` DATE NULL DEFAULT NULL,
  `id_tipoper` INT NULL DEFAULT NULL,
  `formalizada` TINYINT NULL DEFAULT NULL,
  `gls_solicituf` VARCHAR(255) NULL DEFAULT NULL,
  `id_estado` INT NULL DEFAULT NULL,
  `solicitudcol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sysperitos`.`peritajes_has_estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysperitos`.`peritajes_has_estados` (
  `estados_id` INT NOT NULL,
  `peritajes_id` INT NOT NULL,
  PRIMARY KEY (`estados_id`, `peritajes_id`),
  INDEX `fk_estados_has_peritajes_peritajes1_idx` (`peritajes_id` ASC) VISIBLE,
  INDEX `fk_estados_has_peritajes_estados1_idx` (`estados_id` ASC) VISIBLE,
  CONSTRAINT `fk_estados_has_peritajes_estados1`
    FOREIGN KEY (`estados_id`)
    REFERENCES `sysperitos`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estados_has_peritajes_peritajes1`
    FOREIGN KEY (`peritajes_id`)
    REFERENCES `sysperitos`.`peritajes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
